version: "3.9"

services:
  frontend:
    extends:
      file: ../tradeport-frontend/docker-compose.yml
      service: frontend
    networks: [my_network]

  identityservice:
    extends:
      file: ../tradeport-backend-identity/UserManagement/docker-compose.yml
      service: identityservice
    environment:
      - AWS_REGION=ap-southeast-1
      - ASPNETCORE_URLS=http://+:80     # app listens on 7237 inside the container      
    ports:
      - "8087:80"                      # host:container  ← use a free host port
    networks:
      - my_network

  productservice:
    extends:
     file: ../tradeport-backend-productservice/ProductManagement/docker-compose.yml
     service: productservice
    environment:
     - AWS_REGION=ap-southeast-1
     - ASPNETCORE_URLS=http://+:80
    ports:
     - "8088:80"
    networks:
     - my_network

networks:
  my_network:
    external: true