services:
  mssql: 
    extends:
      file: ../tradeport-backend-mssql/docker-compose.yml
      service: mssql
    networks:
      - my_network
      
  frontend:
    extends:
      file: ../tradeport-frontend/docker-compose.yml
      service: frontend
    networks:
      - my_network

  productservice:
    extends:
      file: ../tradeport-backend-productservice/docker-compose.yml
      service: productservice
    networks:
      - my_network
      
  identityservice:
    extends:
      file: ../tradeport-backend-identity/docker-compose.yml
      service: identityservice
    networks:
      - my_network
      

networks:
  my_network:
    external: true
