services:
  mssql:
    build: ../tradeport-backend-mssql
    ports:
      - "1433:1433"
    networks:
      - my_network

  frontend:
    build: ../tradeport-frontend
    ports:
      - "3001:3001"
    environment: 
      - PORT=3001
    networks:
     - my_network  

  productservice:
    build: ../tradeport-backend-productservice
    ports:
      - "3016:3016"
    environment:
      - ASPNETCORE_URLS=http://+:3016
      - DB_USER=sa
      - DB_PASSWORD=Your_password123
      - DB_SERVER=mssql
      - DB_DATABASE=tradeportdb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
