jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_ssh_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
      TF_LOG: DEBUG  # Enable Terraform debugging
      TF_LOG_PATH: terraform-debug.log  # Save debug logs to a file

    steps:
      - name: Debug Secrets
        run: |
          echo "SSH_FINGERPRINT=${{ secrets.SSH_FINGERPRINT }}"
          echo "DO_ACCESS_TOKEN=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform (Debugging Enabled)
        run: |
          export TF_LOG=DEBUG
          terraform init -upgrade | tee terraform-debug.log
        working-directory: terraform

      - name: Plan Terraform (Debugging Enabled)
        id: plan
        run: |
          export TF_LOG=DEBUG
          terraform plan -out=tfplan -parallelism=5 \
            -var="do_token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
            -var="ssh_fingerprint=${{ secrets.SSH_FINGERPRINT }}" | tee terraform-debug.log
        working-directory: terraform

      - name: Show Plan If Failure Occurs
        if: steps.plan.outcome == 'failure'
        run: terraform show -no-color tfplan
        working-directory: terraform

      - name: Apply Terraform (Corrected Command)
        run: |
          export TF_LOG=DEBUG
          terraform apply -auto-approve "tfplan" \
            -var="do_token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
        working-directory: terraform

      - name: Get Droplet IP
        id: get_ip
        run: |
          DROPLET_IP=$(terraform output -raw droplet_ip)
          echo "DROPLET_IP=$DROPLET_IP" >> $GITHUB_OUTPUT
        working-directory: terraform
    outputs:
      droplet_ip: ${{ steps.get_ip.outputs.DROPLET_IP }}
